networks:
  dev:


services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1423
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: 1423
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-p1423"]
      interval: 5s
      timeout: 5s
      retries: 15
    command: 
      --default-authentication-plugin=caching_sha2_password
      --skip-log-bin
      --log-slave-updates=OFF
    networks:
      - dev

  backend:
    build: ./project
    container_name: backend
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: 1423
      DB_NAME: test
    volumes:
      - ./project:/app/project
      - ./frontend:/app/frontend
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - dev

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './frontend/static:/usr/share/nginx/html/static'
    depends_on:
      - backend
    networks:
      - dev

volumes:
  mysql_data:
