version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: library_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1423
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: 1423
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-p1423"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  app:
    build: .
    container_name: fullstack_app
    ports:
      - "8000:8000"  
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: 1423
      DB_NAME: test
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network


volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge