"""Add column

Revision ID: 986707eedd5b
Revises: 
Create Date: 2025-03-03 14:51:53.429504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '986707eedd5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('books_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contents', 'books', ['books_id'], ['id'])
    op.drop_column('contents', 'book_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_column('contents', 'books_id')
    # ### end Alembic commands ###
